import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F3F4F6' },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  header: { padding: 20, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
  title: { fontSize: 24, fontWeight: 'bold', color: '#111827' },
  subtitleActive: { fontSize: 16, color: '#EF4444', marginTop: 4, fontWeight: '600' },
  subtitleNeutral: { fontSize: 16, color: '#6B7280', marginTop: 4 },
  emoji: { fontSize: 60, marginBottom: 20 },
  emptyText: { fontSize: 18, fontWeight: 'bold', color: '#374151', textAlign: 'center' },
  listContainer: { padding: 16, paddingBottom: 100 },

  templateCard: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 16, marginBottom: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', elevation: 2 },
  templateName: { fontSize: 18, fontWeight: 'bold', color: '#1F2937' },
  templateCount: { fontSize: 14, color: '#6B7280', marginTop: 4 },
  startButton: { backgroundColor: '#3B82F6', paddingVertical: 10, paddingHorizontal: 16, borderRadius: 8 },
  startButtonText: { color: 'white', fontWeight: 'bold', fontSize: 14 },

  exerciseCardWrapper: { backgroundColor: '#FFFFFF', borderRadius: 12, marginBottom: 12, elevation: 2, overflow: 'hidden' },
  exerciseCardCompleted: { opacity: 0.72, backgroundColor: '#F9FAFB' },
  exerciseCardBody: { padding: 16 },
  exerciseHeaderRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 12 },
  editExerciseButton: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999, backgroundColor: '#EFF6FF', marginLeft: 12 },
  editExerciseButtonText: { color: '#2563EB', fontWeight: '700', fontSize: 12 },

  exerciseName: { fontSize: 18, fontWeight: 'bold', color: '#1F2937', marginBottom: 8 },
  textCompleted: { textDecorationLine: 'line-through', color: '#6B7280' },
  exerciseInfoRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, backgroundColor: '#F9FAFB', padding: 10, borderRadius: 8 },
  exerciseDetails: { fontSize: 15, color: '#4B5563' },
  bold: { fontWeight: 'bold', color: '#111827' },
  editIcon: { fontSize: 16, color: '#9CA3AF' },

  seriesList: { marginTop: 14, gap: 10 },
  seriesRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F9FAFB', borderRadius: 10, padding: 12, borderWidth: 1, borderColor: '#E5E7EB' },
  seriesRowCompleted: { backgroundColor: '#ECFDF5', borderColor: '#A7F3D0' },
  seriesCheckbox: { width: 24, height: 24, borderRadius: 12, borderWidth: 2, borderColor: '#D1D5DB', justifyContent: 'center', alignItems: 'center', marginRight: 12, backgroundColor: '#FFFFFF' },
  seriesCheckboxChecked: { backgroundColor: '#10B981', borderColor: '#10B981' },
  seriesCheckmark: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 14, marginTop: -1 },
  seriesTitle: { fontSize: 15, fontWeight: '700', color: '#1F2937' },
  seriesSubtitle: { fontSize: 14, color: '#4B5563', marginTop: 2 },

  restOverlayRoot: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  restOverlayAndroidFallback: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(2, 6, 23, 0.72)' },
  restOverlayDim: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(2, 6, 23, 0.42)' },
  restOverlayContent: { alignItems: 'center', paddingHorizontal: 24 },
  restOverlayIcon: { fontSize: 40, color: '#3B82F6', marginBottom: 10, fontWeight: '700' },
  restOverlayTitle: { fontSize: 36, color: '#D5E2F3', fontWeight: '600', marginBottom: 6 },
  restOverlaySeconds: { fontSize: 116, lineHeight: 116, color: '#3B82F6', fontWeight: '800', marginBottom: 6 },
  restOverlaySubtitle: { fontSize: 32, color: '#7F92AE', fontWeight: '500', marginBottom: 28 },
  restOverlaySkipButton: { backgroundColor: '#1E2A3C', borderRadius: 999, paddingVertical: 14, paddingHorizontal: 42 },
  restOverlaySkipText: { color: '#E9EEF7', fontSize: 32, fontWeight: '700' },

  addExerciseBtn: { backgroundColor: '#E0E7FF', padding: 16, borderRadius: 12, alignItems: 'center', marginTop: 10, borderWidth: 1, borderColor: '#C7D2FE', borderStyle: 'dashed' },
  addExerciseBtnText: { color: '#4F46E5', fontWeight: 'bold', fontSize: 16 },

  footer: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 16, backgroundColor: '#FFFFFF', borderTopWidth: 1, borderTopColor: '#E5E7EB', elevation: 10 },
  finishButton: { paddingVertical: 16, borderRadius: 12, alignItems: 'center' },
  finishButtonPending: { backgroundColor: '#A7F3D0' },
  finishButtonReady: { backgroundColor: '#10B981' },
  finishButtonText: { color: 'white', fontSize: 18, fontWeight: 'bold' },
  finishButtonTextPending: { color: '#065F46' },
  finishButtonTextReady: { color: '#FFFFFF' },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, maxHeight: '90%', elevation: 20 },
  modalHeader: { marginBottom: 20, alignItems: 'center' },
  modalTitle: { fontSize: 20, fontWeight: 'bold', color: '#111827' },
  formContainer: { marginBottom: 24 },
  inputGroup: { marginBottom: 16 },
  seriesEditorList: { marginBottom: 8 },
  inputLabel: { fontSize: 14, fontWeight: '600', color: '#374151', marginBottom: 8 },
  textInput: { backgroundColor: '#F9FAFB', borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 8, padding: 12, fontSize: 16, color: '#111827' },
  modalActions: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, marginBottom: 20 },
  cancelButton: { flex: 1, backgroundColor: '#F3F4F6', paddingVertical: 14, borderRadius: 12, alignItems: 'center' },
  cancelButtonText: { color: '#4B5563', fontSize: 16, fontWeight: '600' },
  saveButton: { flex: 2, backgroundColor: '#3B82F6', paddingVertical: 14, borderRadius: 12, alignItems: 'center' },
  saveButtonText: { color: 'white', fontSize: 16, fontWeight: 'bold' },
  deleteButton: { marginTop: 10, paddingVertical: 12, alignItems: 'center' },
  deleteButtonText: { color: '#EF4444', fontSize: 16, fontWeight: '600' },
  cancelSessionBtn: {
    backgroundColor: '#FEE2E2',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  cancelSessionBtnText: {
    color: '#EF4444',
    fontWeight: 'bold',
    fontSize: 14,
  },
});
